spring:
  application:
    name: monitoring

  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring
    username: monitoring
    password: monitoring

  data:
    web:
      pageable:
        max-page-size: 200

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true

  web:
    error:
      include-message: always
      include-stacktrace: always

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

app:
  batch:
    max-size: 1000