spring:
  application:
    name: monitoring

  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring
    username: monitoring
    password: monitoring

  data:
    web:
      pageable:
        max-page-size: 200

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true

app:
  batch:
    max-size: 1000